#include <assert.h>
#include <stdlib.h>
#include "../src/uv_mapping.h"

#define CHECK_ERR(err) assert(uvwasi__translate_uv_error(UV_ ## err ) ==      \
                              UVWASI_ ## err)

int main(void) {
  /* Verify error code translation. */
  CHECK_ERR(E2BIG);
  CHECK_ERR(EADDRINUSE);
  CHECK_ERR(EADDRNOTAVAIL);
  CHECK_ERR(EAFNOSUPPORT);
  CHECK_ERR(EAGAIN);
  CHECK_ERR(EALREADY);
  CHECK_ERR(EBADF);
  CHECK_ERR(EBUSY);
  CHECK_ERR(ECANCELED);
  CHECK_ERR(ECONNABORTED);
  CHECK_ERR(ECONNREFUSED);
  CHECK_ERR(ECONNRESET);
  CHECK_ERR(EDESTADDRREQ);
  CHECK_ERR(EEXIST);
  CHECK_ERR(EFAULT);
  CHECK_ERR(EFBIG);
  CHECK_ERR(EHOSTUNREACH);
  CHECK_ERR(EINTR);
  CHECK_ERR(EINVAL);
  CHECK_ERR(EIO);
  CHECK_ERR(EISCONN);
  CHECK_ERR(EISDIR);
  CHECK_ERR(ELOOP);
  CHECK_ERR(EMFILE);
  CHECK_ERR(EMLINK);
  CHECK_ERR(EMSGSIZE);
  CHECK_ERR(ENAMETOOLONG);
  CHECK_ERR(ENETDOWN);
  CHECK_ERR(ENETUNREACH);
  CHECK_ERR(ENFILE);
  CHECK_ERR(ENOBUFS);
  CHECK_ERR(ENODEV);
  CHECK_ERR(ENOENT);
  CHECK_ERR(ENOMEM);
  CHECK_ERR(ENOPROTOOPT);
  CHECK_ERR(ENOSPC);
  CHECK_ERR(ENOSYS);
  CHECK_ERR(ENOTCONN);
  CHECK_ERR(ENOTDIR);
  CHECK_ERR(ENOTEMPTY);
  CHECK_ERR(ENOTSOCK);
  CHECK_ERR(ENOTSUP);
  CHECK_ERR(ENXIO);
  CHECK_ERR(EPERM);
  CHECK_ERR(EPIPE);
  CHECK_ERR(EPROTO);
  CHECK_ERR(EPROTONOSUPPORT);
  CHECK_ERR(EPROTOTYPE);
  CHECK_ERR(ERANGE);
  CHECK_ERR(EROFS);
  CHECK_ERR(ESPIPE);
  CHECK_ERR(ESRCH);
  CHECK_ERR(ETIMEDOUT);
  CHECK_ERR(ETXTBSY);
  CHECK_ERR(EXDEV);

  /* EACCES is no longer consistently named. */
  assert(uvwasi__translate_uv_error(UV_EACCES) == UVWASI_EACCESS);

  assert(uvwasi__translate_uv_error(0) == UVWASI_ESUCCESS);
  assert(uvwasi__translate_uv_error(1) == 1);
  assert(uvwasi__translate_uv_error(-99999) == UVWASI_ENOSYS);

  return 0;
}
